In [3]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow.eager

ModuleNotFoundError: No module named 'tensorflow.contrib'

In [2]:
tf.__version__

'2.7.0'

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
t

array([0., 1., 2., 3., 4., 5., 6.])

In [3]:
t.ndim

1

In [4]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
t.ndim # = rank of array

2

In [5]:
t.shape

(4, 3)

In [6]:
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[1], [2]])

tf.matmul(m1, m2) # = np.dot

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 5],
       [11]])>

In [7]:
x = [[1., 2.],
     [3., 4.]]

print(tf.reduce_mean(x))

tf.Tensor(2.5, shape=(), dtype=float32)


In [8]:
tf.reduce_mean(x[1])

<tf.Tensor: shape=(), dtype=float32, numpy=3.5>

In [9]:
tf.reduce_mean(x, axis=0) # means of columns

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [10]:
tf.reduce_mean(x, axis=-1) # means of rows

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [11]:
x = [[5, 7, 1],
     [1, 3, 0]]

tf.argmax(x, axis=0) # argmax: maximum 값의 위치

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0], dtype=int64)>

In [12]:
t = np.array([[[1., 2., 3.],
               [4., 5., 6.]],
               
              [[7., 8., 9.],
               [10., 11., 12.]]])
t.shape

(2, 2, 3)

- 보통 reshape 할 때 shape=(x, y, z)에서 shape의 마지막 값(z)는 그대로 두는게 일반적

In [13]:
tf.reshape(t, shape=[-1, 3])

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])>

In [14]:
tf.reshape(t, shape=[-1, 1, 3])

<tf.Tensor: shape=(4, 1, 3), dtype=float64, numpy=
array([[[ 1.,  2.,  3.]],

       [[ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.]],

       [[10., 11., 12.]]])>

In [15]:
tf.squeeze([[1], [2], [3]]) # squeeze: 말 그대로 고차원 -> 저차원으로 바꿔준다고 생각하면 편함

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [16]:
tf.expand_dims([1, 2, 3], 1) # expand_dims: 차원의 수를 늘려줌

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [17]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


### XOR with logistic regression

In [28]:
x_data = np.array([[0,0], [0,1], [1,0], [1,1]])
y_data = np.array([[0], [1], [1], [0]])

x = tf.float32
y = tf.float32
w = tf.Variable(tf.random.normal([2, 1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')

# hypothesis(y-hat) = Wx + b
hypothesis = tf.sigmoid(tf.matmul(x, w) + b)

# cost / loss function
cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1-y) * tf.log(1 - hypothesis))

TypeError: 'DType' object is not callable

<tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([-0.04463868], dtype=float32)>